url: ""
first_name: ""
last_name: ""
email: ""
phone: ""
resume_path: ""
cover_letter_path: ""
linkedin: ""
portfolio: ""
pronouns: ""
Desired Salary: ""
availability: ""

work_authorized: ""
need_sponsorship: ""
relatives: ""

school: ""
degree: ""
discipline: ""
us_citizen: ""

gender: ""
veteran_status: ""
disability_status: ""
are you hispaniclatino: ""
race: ""
